server:
  port: 9002

spring:
  application:
    name: acf

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_URL}/realms/${AUTH_REALM}/protocol/openid-connect/certs

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '50'

  servlet:
    multipart:
      max-request-size: 1500MB
      max-file-size: 1500MB
  flyway:
    enabled: true
    schemas: acf
    default-schema: acf

  jooq:
    sql-dialect: POSTGRES

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: ${log_level:WARN}

application:
  url: ${APP_BASE_URL:asd}
  keycloak:
    admin-auth-client-secret: ${ADMIN_AUTH_CLIENT_SECRET}
    admin-auth-client-id: ${ADMIN_AUTH_CLIENT_ID}
    admin-auth-url: ${AUTH_URL}
    realm: ${AUTH_REALM}
  sms-base-url: ${SMS_BASE_URL:asd}
  minio-url: ${MINIO_URL}
  minio-login: ${MINIO_LOGIN}
  minio-password: ${MINIO_PASSWORD}